ddic/views/admin.py
from flask import Blueprint,redirect,render_template,url_for,current_app,flash
from flask_login import login_required
from ddic.forms.all import PostForm,CommitForm,AdminCommitForm,CategoryForm
from ddic.exts import db
from ddic.models import Post,Category
from ddic.utils import redirect_back
import uuid
bp_admin = Blueprint('admin', __name__)
#文章管理
@bp_admin.route('/post', defaults={'page':1})
@bp_admin.route('/post/list/<int:page>')
def manage_post(page):
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['ITEM_COUNT_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/post_manage.html', posts=posts, pagination=pagination)
#类别管理
@bp_admin.route('/category', defaults={'page':1})
@bp_admin.route('/category/list/<int:page>')
def manage_category(page):
    pagination = Category.query.order_by(Category.name.asc()).paginate(page, per_page=current_app.config['ITEM_COUNT_PER_PAGE'])
    categories = pagination.items
    return render_template('admin/category_manage.html', categories=categories, pagination=pagination)
#新增文章
@bp_admin.route('/post/add', methods=['GET','POST'])
@login_required
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            id=uuid.uuid4().hex,
            title=form.title.data,
            category_id=form.category.data,
            body=form.body.data
        )
        db.session.add(post)
        db.session.commit()
        flash('文章发布成功!!!')
        return redirect(url_for('.add_post'))
    return render_template('admin/post_add.html', form=form)
#删除文章
@bp_admin.route('/post/del/<post_id>', methods=['POST'])
@login_required
def del_post(post_id):
    #返回当前文章列表
    print('Now do the Post delete action , Post id is %s' %post_id)
    post = Post.query.get(post_id)
    db.session.delete(post)
    db.session.commit()
    return redirect_back()
#修改文章
@bp_admin.route('/post/edit/<post_id>', methods=['GET','POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.category_id=form.category.data
        post.body=form.body.data
        db.session.commit()
        flash('文章修改成功!!!')
        return redirect(url_for('.edit_post', post_id=post_id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id
    form.id.data = post.id
    return render_template('admin/post_edit.html', form=form)
#新增类别
@bp_admin.route('/category/add',methods=['GET','POST'])
@login_required
def add_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(
            id = uuid.uuid4().hex,
            name = form.name.data
        )
        db.session.add(category)
        db.session.commit()
        flash('新增类别成功!!!')
        return redirect(url_for('.add_category'))
    return render_template('admin/category_add.html', form=form)
#修改类别
@bp_admin.route('/category/edit/<category_id>', methods=['GET','POST'])
def edit_category(h):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('类别修改成功!!!')
        return redirect(url_for('.edit_category', category_id=category_id))
    form.name.data = category.name
    return render_template('admin/category_edit.html', form=form)
#删除类别
@bp_admin.route('/category/del/<category_id>', methods=['POST'])
@login_required
def del_category(category_id):
    #返回当前文章列表
    print('Now do the Category delete action , Category id is %s' %category_id)
    category = Category.query.get(category_id)
    db.session.delete(category)
    db.session.commit()
    return redirect_back()

ddic/views/blog.py
from flask import Blueprint, redirect,url_for,render_template,session,request,flash,current_app,abort,make_response
from flask_login import login_required
from ddic.models import Post,Category,Comment,PostComment
from ddic.forms.all import PostForm
from ddic.exts import db
from ddic.utils import redirect_back
import uuid
bp_blog = Blueprint('blog', __name__)
#博客首页
@bp_blog.route('/', defaults={'page':1})
@bp_blog.route('/page/<int:page>')
def index(page):
    #page = request.args.get('page', 1, type=int)
    #per_page = current_app.config['ITEM_COUNT_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['ITEM_COUNT_PER_PAGE'])
    posts = pagination.items
    #posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('index.html', posts=posts, pagination=pagination)
@bp_blog.route('/category/<category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ITEM_COUNT_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, posts=posts, pagination=pagination)
#文章详情
@bp_blog.route('/show/<post_id>', methods=['GET','POST'])
def show(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ITEM_COUNT_PER_PAGE']
    pagination = PostComment.query.with_parent(post).order_by(PostComment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    from ddic.forms.all import PostCommitForm
    print('Request method is : >>>>>>>>>>>>>>>>>>>>>>>', request.method)
    form = PostCommitForm()
    if form.validate_on_submit():
        print('save the commit ...')
        pc = PostComment(id=uuid.uuid4().hex, body=form.body.data,post_id=post_id)
        db.session.add(pc)
        db.session.commit()
        return redirect(url_for('.show', post_id=post_id))
    return render_template('blog/show.html', post=post, comments=comments, pagination=pagination, form=form)
#主题切换
@bp_blog.route('/theme/<theme_name>')
def theme(theme_name):
    if theme_name not in current_app.config['BLOG_THEMES'].keys():
        abort(404)
    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=30*24*60*60)
    return response

ddic/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary">
            <a href="#">{{ post.title }}</a>
        </h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small>
                <a href="{{ url_for('blog.show', post_id=post.id) }}">详细</a>
            </small>
        </p>
        <small>
            评论：<a href="#">{{ post.commits|length }}</a>&nbsp;&nbsp;
            类别：<a href="#">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}<hr>{% endif %}
    {% endfor %}
    <br><br>
    <!-- 使用flask Bootstrap插件的分页宏函数实现分页 -->
    {{ render_pagination(pagination) }}
    <!-- 根据Bootstrap官方文档实现分页(注释未用) -->
    {#
        <nav aria-label="Page navigation of posts">
          <ul class="pagination">
            <li class="page-item {% if not pagination.has_prev %}disabled{%endif%}">
              <a class="page-link" href="{{url_for('blog.index', page=pagination.prev_num)}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% for i in range(1, pagination.pages+1) %}
                <li class="page-item {% if pagination.page == i %}active{% endif %}"><a class="page-link" href="{{url_for('blog.index', page=i)}}">{{ i }}</a></li>
            {% endfor %}
            <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
              <a class="page-link" href="{{url_for('blog.index', page=pagination.next_num)}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    #}
{% else %}
    <div class = "tip">
        <h5>还没有发表文章!!!</h5>
        <small><a href="{{ url_for('admin.add_post') }}"><i class="fas fa-pencil-alt"></i>&nbsp;&nbsp;现在写</a></small>
    </div>
{% endif %}

ddic/templates/blog/add.html
{% extends 'parent.html' %}
{% block title %}发表文章{% endblock %}
{% block scripts %}
    {{ static_file('js','ckeditor/ckeditor.js') }}
{% endblock %}
{% block main %}
<div class="container">
    <div class="row">
        <div class = "col">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="row">
                            <div class="col">
                                <div class="alert alert-primary" role="alert">{{ message }}</div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post">
                {{form.csrf_token }}
                <div class="form-group">
                    {{form.title.label}}
                    {{form.title(class='form-control')}}
                    {% if form.title.errors %}
                        {% for message in form.title.errors %}
                            <small class="text-danger">
                                {{ message }}
                            </small>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.category.label }}
                    {{ form.category(class='form-control') }}
                </div>
                <div class="form-group">
                    {{form.body.label}}
                    {{form.body(class='ckeditor')}}
                    {% if form.body.errors %}
                        {% for message in form.body.errors %}
                            <small class="text-danger">
                                {{ message }}
                            </small>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <button class="btn btn-outline-primary" type="submit"><i class="fas fa-cloud-upload-alt"></i>&nbsp;&nbsp;发布</button>&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href = "{{ url_for('blog.index') }}" class="btn btn-outline-secondary"><i class="fas fa-ban"></i>&nbsp;&nbsp;取消</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ddic/templates/blog/category.html
{% extends 'parent.html' %}
{% from 'bootstrap/pagination.html' import render_pagination with context %}
{% block title %}{{ category.name }} - 文章列表{% endblock %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>&lt;&lt;{{ category.name }}&gt;&gt;</h1>
        </div>
    </div><br>
    <div class="row">
        <div class="col-9">
            {% include 'blog/_posts.html' %}
        </div>
        <div class="col-3">
            {% include '_sidebar.html' %}
        </div>
    </div>
</div>
{% endblock %}

ddic/templates/blog/show.html
{% extends 'parent.html' %}
{% from 'bootstrap/pagination.html' import render_pagination with context %}
{% block title %}{{ post.title }}{% endblock %}
{% block main %}
<div class="container">
    <div class="page-header">
        <h1>{{ post.title }}</h1>
        <small>
            类别所属&nbsp;:&nbsp;<a href="#">{{ post.category.name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;
            发布日期&nbsp;:&nbsp;{{ moment(post.timestamp).format('LL')}}
        </small>
    </div><br>
    <div class="row">
        <div class = "col-9">
            <div class="row">
                <div class="col">
                    <!-- 文章正文 -->
                    {{ post.body|safe }}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col" id = "comments">
                    <!-- 文章评论 -->
                    <small>
                        评论数&nbsp;:&nbsp;{{ comments|length }}
                    </small>
                    <hr>
                    {% if comments %}
                        <ul class="list-group">
                            {% for comment in comments %}
                                <li class="list-group-item">
                                    <div class="d-flex w-100 justify-cotent-between">
                                        <small data-toggle="tooltip" data-placement="top" data-delag="500" data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%d%H:%M:%SZ')}}">
                                            {{ moment(comment.timestamp).fromNow() }}
                                        </small>
                                    </div>
                                    <p class="mb-1">{{ comment.body }}</p>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <small class="tip">暂无评论!!!</small>
                    {% endif %}
                     <hr>
                    <form method="post">
                        {{form.csrf_token }}
                        <div class="form-group">
                            {{form.body(class='form-control',rows=3)}}
                            {% if form.body.errors %}
                                {% for message in form.body.errors %}
                                    <small class="text-danger">
                                        {{ message }}
                                    </small>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-outline-primary" type="submit"><i class="fas fa-cloud-upload-alt"></i>&nbsp;&nbsp;评论</button>
                        </div>
                    </form>
                    {% if comments %}
                        {{ render_pagination(pagination, fragment='#comments') }}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-3">
            {% include '_sidebar.html' %}
        </div>
    </div>
</div>
{% endblock %}