ddic/views/admin.py
from flask import Blueprint,redirect,render_template,url_for,current_app,flash
from flask_login import login_required
from ddic.forms.all import PostForm,CommitForm,AdminCommitForm,CategoryForm
from ddic.exts import db
from ddic.models import Post,Category
from ddic.utils import redirect_back
import uuid
bp_admin = Blueprint('admin', __name__)
#文章管理
@bp_admin.route('/post', defaults={'page':1})
@bp_admin.route('/post/list/<int:page>')
def manage_post(page):
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['ITEM_COUNT_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/post_manage.html', posts=posts, pagination=pagination)
#类别管理
@bp_admin.route('/category', defaults={'page':1})
@bp_admin.route('/category/list/<int:page>')
def manage_category(page):
    pagination = Category.query.order_by(Category.name.asc()).paginate(page, per_page=current_app.config['ITEM_COUNT_PER_PAGE'])
    categories = pagination.items
    return render_template('admin/category_manage.html', categories=categories, pagination=pagination)
#新增文章
@bp_admin.route('/post/add', methods=['GET','POST'])
@login_required
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            id=uuid.uuid4().hex,
            title=form.title.data,
            category_id=form.category.data,
            body=form.body.data
        )
        db.session.add(post)
        db.session.commit()
        flash('文章发布成功!!!')
        return redirect(url_for('.add_post'))
    return render_template('admin/post_add.html', form=form)
#删除文章
@bp_admin.route('/post/del/<post_id>', methods=['POST'])
@login_required
def del_post(post_id):
    #返回当前文章列表
    print('Now do the Post delete action , Post id is %s' %post_id)
    post = Post.query.get(post_id)
    db.session.delete(post)
    db.session.commit()
    return redirect_back()
#修改文章
@bp_admin.route('/post/edit/<post_id>', methods=['GET','POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.category_id=form.category.data
        post.body=form.body.data
        db.session.commit()
        flash('文章修改成功!!!')
        return redirect(url_for('.edit_post', post_id=post_id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id
    form.id.data = post.id
    return render_template('admin/post_edit.html', form=form)
#新增类别
@bp_admin.route('/category/add',methods=['GET','POST'])
@login_required
def add_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(
            id = uuid.uuid4().hex,
            name = form.name.data
        )
        db.session.add(category)
        db.session.commit()
        flash('新增类别成功!!!')
        return redirect(url_for('.add_category'))
    return render_template('admin/category_add.html', form=form)
#修改类别
@bp_admin.route('/category/edit/<category_id>', methods=['GET','POST'])
def edit_category(h):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('类别修改成功!!!')
        return redirect(url_for('.edit_category', category_id=category_id))
    form.name.data = category.name
    return render_template('admin/category_edit.html', form=form)
#删除类别
@bp_admin.route('/category/del/<category_id>', methods=['POST'])
@login_required
def del_category(category_id):
    #返回当前文章列表
    print('Now do the Category delete action , Category id is %s' %category_id)
    category = Category.query.get(category_id)
    db.session.delete(category)
    db.session.commit()
    return redirect_back()

ddic/views/article.py
'''
    文章信息维护
'''
from flask import Blueprint,url_for,render_template,redirect,flash,request
import uuid
from ddic.exts import db
from ddic.models import TbArticle,TbAuthor
from ddic.forms.all import ArticleForm
bp_article = Blueprint('article', __name__)
@bp_article.route('/index')
def index():
    #获取该作者所有的文章
    author_id = request.args.get('authorid')
    author = TbAuthor.query.get(author_id)
    articles = author.articles
    return render_template('article/index.html',articles=articles,author=author)
@bp_article.route('/add', methods=['GET','POST'])
def add():
    form = ArticleForm()
    author_id = request.args.get('authorid')
    author = TbAuthor.query.get(author_id)
    form.author_id.data = author_id
    if form.validate_on_submit():
        article = TbArticle(id=uuid.uuid4().hex,title=form.title.data,body=form.body.data,author_id=form.author_id.data)
        db.session.add(article)
        db.session.commit()
        flash('文章发布成功!')
        return redirect(url_for('.add',authorid=form.author_id.data))
    return render_template('article/add.html', form=form,author=author)
@bp_article.route('/edit', methods=['GET','POST'])
def edit():
    form = ArticleForm()
    if request.method == 'GET':
        id = request.args.get('id')
        article = TbArticle.query.get(id)
        form.title.data = article.title
        form.body.data = article.body
        form.id.data = id
        form.author_id.data = article.author_id
    if form.validate_on_submit():
        article = TbArticle.query.get(form.id.data)
        article.title = form.title.data
        article.body = form.body.data
        db.session.commit()
        flash('修改成功!')
        return redirect(url_for('.edit', id=form.id.data))
    return render_template('article/edit.html', form=form)
@bp_article.route('/delete')
def delete():
    id = request.args.get('id')
    article = TbArticle.query.get(id)
    author_id = article.author_id
    db.session.delete(article)
    db.session.commit()
    return redirect(url_for('.index', authorid=author_id))

ddic/views/auth.py
from flask import Blueprint, redirect,url_for,render_template,flash
from flask_login import login_user,current_user,logout_user
from ddic.models import Admin,Login
from ddic.forms.all import LoginForm
from ddic.exts import db
from ddic.utils import redirect_back
import uuid
bp_auth = Blueprint('auth', __name__)
#登录
@bp_auth.route('/login', methods = ['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.filter_by(username=username.lower()).first()
        if admin:
            if admin.validate_password(password):
                login_user(admin, remember)
                #新增登录履历
                login = Login(id=uuid.uuid4().hex,admin_id=admin.id)
                db.session.add(login)
                db.session.commit()
                return redirect_back()
            else:
                flash('密码错误!!!')
        else:
            flash('账号不存在!!!')
    return render_template('auth/login.html', form=form)
#登出
@bp_auth.route('/logout')
#@login_required
def logout():
    logout_user()
    return redirect(url_for('blog.index'))

ddic/views/blog.py
from flask import Blueprint, redirect,url_for,render_template,session,request,flash,current_app,abort,make_response
from flask_login import login_required
from ddic.models import Post,Category,Comment,PostComment
from ddic.forms.all import PostForm
from ddic.exts import db
from ddic.utils import redirect_back
import uuid
bp_blog = Blueprint('blog', __name__)
#博客首页
@bp_blog.route('/', defaults={'page':1})
@bp_blog.route('/page/<int:page>')
def index(page):
    #page = request.args.get('page', 1, type=int)
    #per_page = current_app.config['ITEM_COUNT_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['ITEM_COUNT_PER_PAGE'])
    posts = pagination.items
    #posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('index.html', posts=posts, pagination=pagination)
@bp_blog.route('/category/<category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ITEM_COUNT_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, posts=posts, pagination=pagination)
#文章详情
@bp_blog.route('/show/<post_id>', methods=['GET','POST'])
def show(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ITEM_COUNT_PER_PAGE']
    pagination = PostComment.query.with_parent(post).order_by(PostComment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    from ddic.forms.all import PostCommitForm
    print('Request method is : >>>>>>>>>>>>>>>>>>>>>>>', request.method)
    form = PostCommitForm()
    if form.validate_on_submit():
        print('save the commit ...')
        pc = PostComment(id=uuid.uuid4().hex, body=form.body.data,post_id=post_id)
        db.session.add(pc)
        db.session.commit()
        return redirect(url_for('.show', post_id=post_id))
    return render_template('blog/show.html', post=post, comments=comments, pagination=pagination, form=form)
#主题切换
@bp_blog.route('/theme/<theme_name>')
def theme(theme_name):
    if theme_name not in current_app.config['BLOG_THEMES'].keys():
        abort(404)
    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=30*24*60*60)
    return response

ddic/templates/_sidebar.html
{% if categories %}
<div class="card">
  <div class="card-header">
    Categories
  </div>
  <ul class="list-group list-group-flush">
      {% for category in categories %}
        <li class="list-group-item">
            <a href="{{ url_for('blog.show_category', category_id=category.id) }}">{{ category.name }}</a>
            <span class="badge badge-success float-right">{{ category.posts|length }}</span>
        </li>
      {% endfor %}
  </ul>
</div>
{% endif %}

ddic/templates/base.html
<!DOCTYPE html>
<html lang="en">
{# 显式地使用with context声明传人当前模板的上下文 #}
{% from 'macros/macros.html' import static_file with context %}
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% block title %}Base Title{% endblock %}</title>
    <!-- 使用宏导入静态文件 -->
    {{static_file('icon', 'images/icon/favicon.ico')}}
    {{static_file('css','css/bootstrap.min.css')}}
    {{static_file('css','css/jquery-confirm.min.css')}}
    {{static_file('css','css/all.min.css')}}
    {# --------- 引入子页面自己的css文件 --------- #}
    {% block links %}{% endblock %}
    {{static_file('js','js/jquery-3.6.0.min.js')}}
    {{static_file('js','js/popper.min.js')}}
    {{static_file('js','js/bootstrap.min.js')}}
    {{static_file('js','js/jquery-confirm.min.js')}}
    <!-- 生成执行时间渲染函数 -->
    {{ moment.include_moment(local_js=url_for('static',filename='js/moment/moment-with-locales.js')) }}
    <!-- 设置自动识别显示语言 -->
    {{ moment.locale(auto_detect=True) }}
    {# --------- 引入子页面自己的JavaScript文件 --------- #}
    {% block scripts %}{% endblock %}
    {# --------- 编写子页面自己的css样式 --------- #}
    {% block styles %}{% endblock %}
    {% endblock %}
</head>
<body>
    <header style="margin-top:20px;">
        {% block header %}
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <h1><a href = "{{url_for('index')}}">博客</a></h1>
                    </div>
                </div>
            </div>
        {% endblock %}
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
    <footer>
        {% block footer %}{% endblock %}
    </footer>
    <script>
        $(function(){
            //alert('base is ready')
        })
        {# --------- 引入子页面JavaScritp变量 --------- #}
        {% block variable %}{% endblock %}
        {% block ready %}{% endblock %}
        {# --------- 引入子页面自己的JavaScript函数 --------- #}
        {% block function %}
        function allAlert(){
           $.alert({
               type:'red',
               //icon:'fa fa-info',
               title:'提示',
               content: 'I Am Ready To Go！',
               onClose:function(){

               }
           })
        }
        function allClick(){
            alert('All Click!!!')
        }
        {% endblock %}
    </script>
</body>
</html>

ddic/templates/index.html
{% extends 'parent.html' %}
{% from 'bootstrap/pagination.html' import render_pagination with context %}
{% block title %}博客主页{% endblock %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>{{ admin.blog_title|default('My Blog') }}</h1>
            <samll>{{ admin.blog_sub_title|default('My blog sub title !!!') }}</samll>
        </div>
    </div><br>
    <div class="row">
        <div class="col-9">
            {% if posts %}
                {% for post in posts %}
                    <h3 class="text-primary">
                        <a href="#">{{ post.title }}</a>
                    </h3>
                    <p>
                        {{ post.body|striptags|truncate }}
                        <small>
                            <a href="{{ url_for('blog.show', post_id=post.id) }}">详细</a>
                        </small>
                    </p>
                    <small>
                        评论：<a href="#">{{ post.commits|length }}</a>&nbsp;&nbsp;
                        类别：<a href="#">{{ post.category.name }}</a>
                        <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
                    </small>
                    {% if not loop.last %}<hr>{% endif %}
                {% endfor %}
                <br><br>
                {{ render_pagination(pagination) }}
                {#<nav aria-label="Page navigation of posts">
                  <ul class="pagination">
                    <li class="page-item {% if not pagination.has_prev %}disabled{%endif%}">
                      <a class="page-link" href="{{url_for('blog.index', page=pagination.prev_num)}}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    {% for i in range(1, pagination.pages+1) %}
                        <li class="page-item {% if pagination.page == i %}active{% endif %}"><a class="page-link" href="{{url_for('blog.index', page=i)}}">{{ i }}</a></li>
                    {% endfor %}
                    <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                      <a class="page-link" href="{{url_for('blog.index', page=pagination.next_num)}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                  </ul>
                </nav>#}
            {% else %}
                <div class = "tip">
                    <h5>还没有发表文章!!!</h5>
                    <small><a href="{{ url_for('blog.add') }}"><i class="fas fa-pencil-alt"></i>&nbsp;&nbsp;现在写</a></small>
                </div>
            {% endif %}
        </div>
        <div class="col-3">
            {% include '_sidebar.html' %}
        </div>
    </div>
</div>
{% endblock %}

ddic/templates/parent.html
<!DOCTYPE html>
<html lang="en">
{# 显式地使用with context声明传人当前模板的上下文 #}
{% from 'macros/macros.html' import static_file with context %}
{% from 'bootstrap/nav.html' import render_nav_item  with context %}
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Base Title{% endblock %}</title>
    <!-- 使用宏导入静态文件 -->
    {{static_file('icon', 'images/icon/favicon.ico')}}
    <!-- 动态切换主题 -->
    {{static_file('css','css/themes/%s.min.css' %request.cookies.get('theme', 'bootstrap'))}}
    {{static_file('css','css/jquery-confirm.min.css')}}
    {{static_file('css','css/all.min.css')}}
    {# --------- 引入子页面自己的css文件 --------- #}
    {% block links %}{% endblock %}
    {{static_file('js','js/jquery-3.6.0.min.js')}}
    {{static_file('js','js/popper.min.js')}}
    {{static_file('js','js/bootstrap.min.js')}}
    {{static_file('js','js/jquery-confirm.min.js')}}
    <!-- 生成执行时间渲染函数 -->
    {{ moment.include_moment(local_js=url_for('static',filename='js/moment/moment-with-locales.js')) }}
    <!-- 设置自动识别显示语言 -->
    {{ moment.locale(auto_detect=True) }}
    {# --------- 引入子页面自己的JavaScript文件 --------- #}
    {% block scripts %}{% endblock %}
    {# --------- 编写子页面自己的css样式 --------- #}
    {% block styles %}{% endblock %}
    {% endblock %}
</head>
<body>
    <header style="margin-bottom:65px;">
        {% block header %}
            <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
                <div class = "container-fluid">
                    <a class="navbar-brand" href="{{url_for('blog.index')}}">Blog</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                          {{ render_nav_item('blog.index', '主页') }}
                        </li>
                        <li class="nav-item">
                            {{ render_nav_item('board.index', '留言板') }}
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              主题
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for theme_name, show_name in config['BLOG_THEMES'].items() %}
                                    <a class="dropdown-item" href="{{ url_for('blog.theme', theme_name=theme_name, next=request.full_path) }}">{{ show_name }}</a>
                                {% endfor %}
                            </div>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              管理
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">文章<span class="badge badge-success float-right">{{ post_cout }}</span></a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">分类<span class="badge badge-success float-right">{{ categories|length }}</span></a>
                                <!--a class="dropdown-item" href="#">评论<span class="badge badge-success float-right">{{ unread_comments }}</span></a-->
                            </div>
                        </li>
                        {% endif %}
                      </ul>
                    </div>
                    <div class="row text-right">
                        <div class="col-12">
                            {% if current_user.is_authenticated %}
                                <span class="navbar-text">
                                    Welcome&nbsp;:&nbsp;{{ admin.username|title }}
                                </span>&nbsp;&nbsp;
                                <a href="{{ url_for('auth.logout', next=request.full_path)}}" class="btn btn-outline-info"><i class="fas fa-sign-out-alt"></i></a>
                            {% else %}
                                <a href="{{ url_for('auth.login', next=request.full_path)}}" class="btn btn-outline-info"><i class="fas fa-sign-in-alt"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        {% endblock %}
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
    <footer>
        {% block footer %}{% endblock %}
    </footer>
    <script>
        $(function(){
            //alert('parent is ready')
        })
        {# --------- 引入子页面JavaScritp变量 --------- #}
        {% block variable %}{% endblock %}
        {% block ready %}{% endblock %}
        {# --------- 引入子页面自己的JavaScript函数 --------- #}
        {% block function %}
        function allAlert(){
           $.alert({
               type:'red',
               //icon:'fa fa-info',
               title:'提示',
               content: 'I Am Ready To Go！',
               onClose:function(){

               }
           })
        }
        function allClick(){
            alert('All Click!!!')
        }
        {% endblock %}
    </script>
</body>
</html>