ddic/views/article.py
'''
    文章信息维护
'''
from flask import Blueprint,url_for,render_template,redirect,flash,request
import uuid
from ddic.exts import db
from ddic.models import TbArticle,TbAuthor
from ddic.forms.all import ArticleForm
bp_article = Blueprint('article', __name__)
@bp_article.route('/index')
def index():
    #获取该作者所有的文章
    author_id = request.args.get('authorid')
    author = TbAuthor.query.get(author_id)
    articles = author.articles
    return render_template('article/index.html',articles=articles,author=author)
@bp_article.route('/add', methods=['GET','POST'])
def add():
    form = ArticleForm()
    author_id = request.args.get('authorid')
    author = TbAuthor.query.get(author_id)
    form.author_id.data = author_id
    if form.validate_on_submit():
        article = TbArticle(id=uuid.uuid4().hex,title=form.title.data,body=form.body.data,author_id=form.author_id.data)
        db.session.add(article)
        db.session.commit()
        flash('文章发布成功!')
        return redirect(url_for('.add',authorid=form.author_id.data))
    return render_template('article/add.html', form=form,author=author)
@bp_article.route('/edit', methods=['GET','POST'])
def edit():
    form = ArticleForm()
    if request.method == 'GET':
        id = request.args.get('id')
        article = TbArticle.query.get(id)
        form.title.data = article.title
        form.body.data = article.body
        form.id.data = id
        form.author_id.data = article.author_id
    if form.validate_on_submit():
        article = TbArticle.query.get(form.id.data)
        article.title = form.title.data
        article.body = form.body.data
        db.session.commit()
        flash('修改成功!')
        return redirect(url_for('.edit', id=form.id.data))
    return render_template('article/edit.html', form=form)
@bp_article.route('/delete')
def delete():
    id = request.args.get('id')
    article = TbArticle.query.get(id)
    author_id = article.author_id
    db.session.delete(article)
    db.session.commit()
    return redirect(url_for('.index', authorid=author_id))

ddic/views/author.py
'''
    作者信息维护
'''
from flask import Blueprint, url_for,redirect,render_template,flash,request
from ddic.forms.all import AuthorForm
from ddic.exts import db
from ddic.models import TbAuthor
import uuid
bp_author = Blueprint('author', __name__)
'''
    作者信息主页(新增/列表/删除)
'''
@bp_author.route('/index', methods=['GET','POST'])
def index():
    authors = TbAuthor.query.order_by(TbAuthor.timestamp.desc()).all()
    form = AuthorForm()
    if form.validate_on_submit():
        print('save the author information!!!')
        author = TbAuthor(id=uuid.uuid4().hex,name=form.name.data,phone=form.phone.data)
        db.session.add(author)
        db.session.commit()
        flash('作者信息已保存！')
        return redirect(url_for('.index'))
    return render_template('author/index.html', form=form, authors=authors)
'''
    作者信息修改
'''
@bp_author.route('/edit', methods=['GET','POST'])
def edit():
    form = AuthorForm()
    if request.method == 'GET':
        id = request.args.get('id')
        author = TbAuthor.query.get(id)
        form.name.data = author.name
        form.phone.data = author.phone
        form.id.data = id
    if form.validate_on_submit():
        author = TbAuthor.query.get(form.id.data)
        author.name = form.name.data
        author.phone = form.phone.data
        db.session.commit()
        flash('修改成功！')
        return redirect(url_for('.edit', id=form.id.data))
    return render_template('author/edit.html', form=form,author=author)
@bp_author.route('/delete')
def delete():
    id = request.args.get('id')
    author = TbAuthor.query.get(id)
    db.session.delete(author)
    db.session.commit()
    return redirect(url_for('.index'))

ddic/templates/author/edit.html
{% extends 'base.html' %}
{% block title %}作者信息维护{% endblock %}
<header>
    {% block header %}
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <h1><a href = "{{url_for('author.edit', id=author.id)}}">作者-编辑</a></h1>
                    <small>Administrator : {{ admin_name }}</small>
                </div>
            </div>
        </div>
    {% endblock %}
</header>
{% block main %}
<div class="container">
    <div class="row">
        <div class="col text-right">
            <a href = "{{ url_for('author.index') }}" class="btn btn-outline-secondary"><i class="fas fa-arrow-left"></i>&nbsp;返回列表</a>
        </div>
    </div><br>
    {% if get_flashed_messages() %}
    <div class="row">
        <div class="col">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {% for message in get_flashed_messages() %}
                <small>{{ message }}</small>
              {% endfor %}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col">
          <form method="post">
              <!-- 表单必须填写csrf验证，否则验证会一直无法通过！！！ -->
              {{ form.csrf_token }}
              <div class="mb-3">
                  {{ form.name.label(class='form-label')}}
                  {{ form.name(class='form-control',placeholder='请输入姓名!')}}
                  {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        <small class="text-warning">{{ error }}</small>
                    {% endfor %}
                  {% endif %}
              </div>
              <div class="mb-3">
                  {{ form.phone.label(class='form-label')}}
                  {{ form.phone(class='form-control',placeholder='请输入手机号!')}}
                  {% if form.phone.errors %}
                    {% for error in form.phone.errors %}
                        <small class="text-warning">{{ error }}</small>
                    {% endfor %}
                  {% endif %}
              </div>
              <div class="mb-3">
                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-save"></i>&nbsp;&nbsp;保存</button>&nbsp;&nbsp;&nbsp;&nbsp;
              </div>
              {{ form.id() }}
          </form>
        </div>
    </div>
</div>
{% endblock %}
<script>
    {% block function%}
    {{ super() }}

    {% endblock %}
</script>

ddic/templates/author/index.html
{% extends 'base.html' %}
{% block title %}作者信息维护{% endblock %}
<header>
    {% block header %}
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <h1><a href = "{{url_for('author.index')}}">作者</a></h1>
                    <small class="text-secondary">Administrator : {{ admin.name }}</small>
                </div>
            </div>
        </div>
    {% endblock %}
</header>
{% block main %}
<div class="container">
    {% if get_flashed_messages() %}
    <div class="row">
        <div class="col">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {% for message in get_flashed_messages() %}
                <small>{{ message }}</small>
              {% endfor %}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col">
          <form method="post">
              <!-- 表单必须填写csrf验证，否则验证会一直无法通过！！！ -->
              {{ form.csrf_token }}
              <div class="mb-3">
                  {{ form.name.label(class='form-label')}}
                  {{ form.name(class='form-control',placeholder='请输入姓名!')}}
                  {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        <small class="text-warning">{{ error }}</small>
                    {% endfor %}
                  {% endif %}
              </div>
              <div class="mb-3">
                  {{ form.phone.label(class='form-label')}}
                  {{ form.phone(class='form-control',placeholder='请输入手机号!')}}
                  {% if form.phone.errors %}
                    {% for error in form.phone.errors %}
                        <small class="text-warning">{{ error }}</small>
                    {% endfor %}
                  {% endif %}
              </div>
              <div class="mb-3">
                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-save"></i>&nbsp;&nbsp;保存</button>&nbsp;&nbsp;&nbsp;&nbsp;
              </div>
          </form>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col" width="10%">#</th>
                  <th scope="col" width="25%">姓名</th>
                  <th scope="col" width="30%">手机号</th>
                  <th scope="col" width="15%">文章数</th>
                  <th scope="col" width="20%">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for author in authors%}
                    <tr>
                      <th scope="row">{{ loop.index }}</th>
                      <td>{{ author.name }}</td>
                      <td>{{ author.phone }}</td>
                      <td>{{ author.articles|length }}</td>
                      <td>
                          <a href="{{ url_for('article.index', authorid=author.id)}}" class="btn btn-outline-info btn-sm"><i class="fas fa-file-alt"></i>&nbsp;文章</a>
                          <a href="{{ url_for('author.edit', id=author.id) }}" class="btn btn-outline-success btn-sm"><i class="fas fa-edit"></i>&nbsp;编辑</a>
                          <a href="javascript:doDelete('{{url_for('author.delete', id=author.id)}}')" class="btn btn-outline-danger btn-sm"><i class="fas fa-trash-alt"></i>&nbsp;删除</a>
                      </td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}
<script>
    {% block function%}
    {{ super() }}
    function doDelete(url){
        $.confirm({
            title: '提示!',
            content: '确定要删除？',
            boxWidth: '25%',
            useBootstrap: false,
            type: 'red',
            typeAnimated: true,
            buttons: {
                cancel:{
                    text:"取消"
                },
                confirm:{
                    text:"确定",
                    action:function () {
                        window.location.href = url
                    }
                }
            }
        });
    }
    {% endblock %}
</script>